{{- if .Values.elasticsearch.pushIndexTemplate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "opendistro-es.fullname" . }}-index-template
  namespace: {{ .Release.Namespace }}
  #annotations:
  #  "helm.sh/hook": post-install
  #  "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: es-init
          image: nybbledevcontainerregistry.azurecr.io/nybbledev/nybble-toolbox:latest
          env:
            - name: client.node
              value: {{ template "opendistro-es.fullname" . }}-client-service:9200
          command: [ 'sh', '-c', 'until [curl -XPUT --insecure -u admin:admin https://$(client.node) == "Open Distro Security not initialized."]; do echo "Waiting for Elasticsearch security initialization"; sleep 5; done;' ]
      containers:
        - name: {{ template "opendistro-es.fullname" . }}-index-template
          image: nybbledevcontainerregistry.azurecr.io/nybbledev/nybble-toolbox:latest
          env:
            - name: index.template.path
              value: {{ .Values.elasticsearch.pushIndexTemplate.templatePath }}
            - name: client.node
              value: {{ template "opendistro-es.fullname" . }}-client-service:9200
          command: ["/bin/sh"]
          args: ["-c", "wget --output-document nybble-es-template.json $(index.template.path) && curl -XPUT --insecure -u admin:admin -H 'Content-Type: application/json' https://$(client.node)/_index_template/nybble-template -d@nybble-es-template.json"]
{{- end }}