{{- if .Values.elasticsearch.pushIndexTemplate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
  name: {{ template "opendistro-es.fullname" . }}-index-template
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "post-install"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: {{ template "opendistro-es.fullname" . }}-index-template
        image: busybox:latest
        env:
        - name: index.template.path
          value: {{ .Values.elasticsearch.pushIndexTemplate.templatePath }}
        - name: client.node
          value: {{ template "opendistro-es.fullname" . }}-client-service:9200
        command: ["/bin/sh"]
        args: ["-c", "wget --output-document nybble-es-template.json $(index.template.path) && cat nybble-es-template.json"] #curl -XPUT --insecure -u admin:admin -H 'Content-Type: application/json' https://{{ template "opendistro-es.fullname" . }}-client-service:9200/_index_template/nybble-template -@nybble-es-template.json
{{- end }}